name: Go

on:
  workflow_dispatch:
  push:
    paths:
      - "*.go"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "*.go"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go.yml"

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          check-latest: true
          cache: true

      - name: Check Go modules
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
          go mod verify

      - name: Build
        run: go build -v  ./...
